name: xmonad-config
version: "1.0"
synopsis: Michael Sloan's xmonad configuration
author: Michael Sloan
license: MIT
github: mgsloan/dotfiles.git
dependencies:
- async
- base
- bytestring
- containers
- directory
- filepath
- http-client
- http-client-tls
- monad-loops
- process
- stm
- text
- time
- xmonad
- xmonad-contrib
executables:
  custom-xmonad:
    main: xmonad.hs
    source-dirs: src
    ghc-options:
    - -Wall
