resolver: lts-13.1
flags:
  xmonad-contrib:
    testing: false
    use_xft: true
  xmonad:
    testing: false
packages:
- .
- errlog-filter/
- xmonad/
- xmonad-contrib/
- typed-process/
# - hoggl/
extra-deps:
- X11-1.8
